version: '3.9'
services:
  couchdb:
    image: couchdb:3
    container_name: chatzap-couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    volumes:
      - couchdb-data:/opt/couchdb/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://admin:admin@localhost:5984/_up"]
      interval: 5s
      timeout: 3s
      retries: 20
  setup:
    image: curlimages/curl:8.11.1
    depends_on:
      couchdb:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >-
      "curl -X PUT http://admin:admin@couchdb:5984/chatzap &&
       curl -X PUT http://admin:admin@couchdb:5984/_users &&
       curl -X PUT http://admin:admin@couchdb:5984/_replicator &&
       curl -X PUT http://admin:admin@couchdb:5984/_global_changes &&
       # Enable CORS
       curl -X PUT http://admin:admin@couchdb:5984/_node/_local/_config/httpd/enable_cors -d '"true"' &&
       curl -X PUT http://admin:admin@couchdb:5984/_node/_local/_config/cors/origins -d '"*"' &&
       curl -X PUT http://admin:admin@couchdb:5984/_node/_local/_config/cors/credentials -d '"true"' &&
       curl -X PUT http://admin:admin@couchdb:5984/_node/_local/_config/cors/methods -d '"GET, PUT, POST, HEAD, DELETE"' &&
       curl -X PUT http://admin:admin@couchdb:5984/_node/_local/_config/cors/headers -d '"accept, authorization, content-type, origin, referer, x-csrf-token"' &&
       echo Setup complete"
volumes:
  couchdb-data:
