-- ============================================================================
--  PDV RESTAURANTE — Schema inicial (PostgreSQL 15+)
--  Módulos: Estoque + Ficha Técnica | Atendimento (Garçom) | Caixa & Mesas
--
--  Convenções:
--  • Dinheiro: NUMERIC(12,2). Quantidades de estoque: NUMERIC(12,3)
--    (essencial em restaurante: gramas, ml, frações de kg/litro).
--  • Preços viram "snapshot" nos itens do pedido (mudar o cardápio não
--    altera contas abertas).
--  • O saldo de estoque NUNCA é editado direto: é a soma dos movimentos
--    (fonte da verdade auditável: compra, venda, perda, ajuste).
--  • A baixa automática por venda roda em trigger quando o item é ENVIADO
--    (configurável: ENVIO | PRONTO | ENTREGA) e é estornada se o item for
--    cancelado depois.
--  • PKs bigint (simples de começar). Se um dia houver multi-filia ou
--    sincronização offline, migrar p/ UUID (gen_random_uuid()).
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 0. ENUMS
-- ----------------------------------------------------------------------------
CREATE TYPE tipo_unidade          AS ENUM ('MASSA', 'VOLUME', 'UNIDADE');
CREATE TYPE tipo_movimento_estoque AS ENUM (
  'ENTRADA',            -- compra recebida
  'SAIDA_VENDA',        -- baixa automática por venda (via ficha técnica)
  'AJUSTE_POSITIVO',    -- contagem de estoque (sobrou)
  'AJUSTE_NEGATIVO',    -- contagem de estoque (faltou)
  'PERDA',              -- estragou, venceu, caiu no chão
  'CONSUMO_INTERNO'     -- refeição de funcionário, teste de cozinha
);
CREATE TYPE tipo_origem_movimento  AS ENUM (
  'COMPRA_FORNECEDOR', 'BAIXA_VENDA', 'CONTAGEM', 'CANCELAMENTO_ITEM', 'OUTRO'
);
CREATE TYPE tipo_status_mesa       AS ENUM ('LIVRE', 'OCUPADA', 'AGUARDANDO_CONTA', 'RESERVADA');
CREATE TYPE tipo_status_pedido     AS ENUM ('ABERTO', 'FECHADO', 'CANCELADO');
CREATE TYPE tipo_status_item       AS ENUM ('RASCUNHO', 'ENVIADO', 'EM_PREPARO', 'PRONTO', 'ENTREGUE', 'CANCELADO');
CREATE TYPE tipo_remessa           AS ENUM ('ENTRADA', 'PRINCIPAL', 'SOBREMESA', 'LIVRE');
CREATE TYPE tipo_status_remessa    AS ENUM ('ENVIADA', 'CONCLUIDA', 'CANCELADA');
CREATE TYPE tipo_estacao           AS ENUM ('COZINHA', 'BAR');
CREATE TYPE tipo_status_impressao  AS ENUM ('PENDENTE', 'EM_IMPRESSAO', 'IMPRESSA', 'FALHA');
CREATE TYPE tipo_status_conta      AS ENUM ('ABERTA', 'FECHADA', 'CANCELADA');
CREATE TYPE tipo_forma_pagamento   AS ENUM ('DINHEIRO', 'PIX', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'VALE_ALIMENTACAO', 'VALE_REFEICAO', 'OUTRO');
CREATE TYPE tipo_status_pagamento  AS ENUM ('PENDENTE', 'APROVADO', 'CANCELADO');
CREATE TYPE tipo_status_caixa      AS ENUM ('ABERTO', 'FECHADO');
CREATE TYPE tipo_movimento_caixa   AS ENUM ('SANGRIA', 'SUPRIMENTO');
CREATE TYPE tipo_papel_usuario     AS ENUM ('GARCOM', 'CAIXA', 'COZINHEIRO', 'BAR', 'GERENTE', 'ADMIN');

-- ----------------------------------------------------------------------------
-- 1. BASE / CADASTROS
-- ----------------------------------------------------------------------------
CREATE TABLE usuario (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          TEXT NOT NULL,
  email         TEXT,
  pin_hash      TEXT,                                  -- PIN p/ operar o PDV (hash bcrypt no backend)
  papel         tipo_papel_usuario NOT NULL,
  ativo         BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em     TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- login por e-mail exige unicidade (nulos = usuário sem e-mail, ok repetir)
CREATE UNIQUE INDEX ux_usuario_email ON usuario (lower(email)) WHERE email IS NOT NULL;

-- Configuração única do restaurante (linha id=1)
CREATE TABLE config_restaurante (
  id                  BIGINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  nome                TEXT NOT NULL DEFAULT 'Meu Restaurante',
  gorjeta_percentual  NUMERIC(5,2) NOT NULL DEFAULT 10.00, -- % sugerido de serviço
  gorjeta_incluir_por_padrao BOOLEAN NOT NULL DEFAULT TRUE,
  baixa_estoque_em    TEXT NOT NULL DEFAULT 'ENVIO'
                      CHECK (baixa_estoque_em IN ('ENVIO', 'PRONTO', 'ENTREGA')),
  tempo_medio_prato_min INT  NOT NULL DEFAULT 25          -- p/ alertas de atraso
);

CREATE TABLE unidade_medida (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sigla     TEXT NOT NULL UNIQUE,            -- g, kg, ml, l, un, dz
  nome      TEXT NOT NULL,
  tipo      tipo_unidade NOT NULL
);

CREATE TABLE fornecedor (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome              TEXT NOT NULL,
  cnpj              TEXT,
  telefone          TEXT,
  email             TEXT,
  prazo_entrega_dias SMALLINT,
  ativo             BOOLEAN NOT NULL DEFAULT TRUE
);

-- ----------------------------------------------------------------------------
-- 2. MÓDULO ESTOQUE
-- ----------------------------------------------------------------------------
CREATE TABLE insumo (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome                TEXT NOT NULL,
  unidade_estoque_id  BIGINT NOT NULL REFERENCES unidade_medida (id), -- unidade "base" (kg, l, un)
  unidade_compra_id   BIGINT REFERENCES unidade_medida (id),          -- unidade de compra (fardo, saco, cx)
  fator_compra        NUMERIC(12,3) NOT NULL DEFAULT 1
                      CHECK (fator_compra > 0),  -- 1 unidade de compra = fator_compra unidades de estoque
  custo_unitario      NUMERIC(12,4) NOT NULL DEFAULT 0,  -- custo POR UNIDADE DE ESTOQUE (atualizado nas compras)
  estoque_minimo      NUMERIC(12,3) NOT NULL DEFAULT 0,  -- alerta de falta
  estoque_maximo      NUMERIC(12,3),                     -- p/ sugerir qtd de compra
  fornecedor_padrao_id BIGINT REFERENCES fornecedor (id),
  valido_dias         SMALLINT,                           -- vida útil média (p/ previsão de compra)
  ativo               BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_insumo_nome ON insumo (lower(nome)) WHERE ativo;

CREATE TABLE estoque_movimento (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  insumo_id       BIGINT NOT NULL REFERENCES insumo (id),
  tipo            tipo_movimento_estoque NOT NULL,
  quantidade      NUMERIC(12,3) NOT NULL CHECK (quantidade > 0), -- SEMPRE positiva; o sinal vem do tipo
  custo_unitario  NUMERIC(12,4),                                 -- custo da unidade de estoque na época
  origem          tipo_origem_movimento NOT NULL DEFAULT 'OUTRO',
  pedido_item_id  BIGINT,          -- preenchido pela baixa de venda (FK adicionada após criar pedido_item)
  usuario_id      BIGINT REFERENCES usuario (id),
  motivo          TEXT,            -- ex.: "Nota Fiscal 1023", "Marmita da equipe", "Item 43 cancelado"
  data_movimento  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_estoque_mov_insumo_data ON estoque_movimento (insumo_id, data_movimento DESC);
CREATE INDEX ix_estoque_mov_pedido_item ON estoque_movimento (pedido_item_id) WHERE pedido_item_id IS NOT NULL;

-- ----------------------------------------------------------------------------
-- 3. CARDAPIO + FICHA TECNICA
-- ----------------------------------------------------------------------------
CREATE TABLE estacao (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          TEXT NOT NULL,                    -- "Cozinha Quente", "Bar"
  tipo          tipo_estacao NOT NULL,            -- COZINHA | BAR (define a fila de impressão)
  ativo         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE impressora (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estacao_id    BIGINT NOT NULL REFERENCES estacao (id),
  nome          TEXT NOT NULL,                    -- "TM-T20 Cozinha"
  ip            TEXT NOT NULL,
  porta         INT  NOT NULL DEFAULT 9100,       -- RAW/ESC-POS por TCP na LAN
  papel_mm      SMALLINT NOT NULL DEFAULT 80,
  ativa         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE categoria (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome        TEXT NOT NULL,                      -- Entradas, Massas, Bebidas...
  estacao_id  BIGINT REFERENCES estacao (id),     -- p/ onde esta categoria imprime por padrão
  sort        INT NOT NULL DEFAULT 0,
  ativo       BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX ux_categoria_nome ON categoria (lower(nome)) WHERE ativo;

CREATE TABLE produto (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome                 TEXT NOT NULL,
  descricao            TEXT,
  categoria_id         BIGINT NOT NULL REFERENCES categoria (id),
  preco                NUMERIC(12,2) NOT NULL CHECK (preco >= 0),
  -- override da estação da categoria (ex.: "Batata Frita" sai na cozinha,
  -- mas "Porção do Bar" imprime no bar)
  estacao_id           BIGINT REFERENCES estacao (id),
  -- produtos SEM ficha técnica que são o próprio insumo (long neck, lata de
  -- refrigerante, garrafa de água): a venda dá baixa 1:1 neste insumo.
  insumo_vinculado_id  BIGINT REFERENCES insumo (id),
  unidade_porcao       TEXT,                       -- "prato ~350 g", "copo 300 ml"
  ativo                BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_produto_nome ON produto (lower(nome)) WHERE ativo;

-- Cabeçalho da ficha técnica (1 por produto)
CREATE TABLE ficha_tecnica (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id     BIGINT NOT NULL UNIQUE REFERENCES produto (id) ON DELETE CASCADE,
  rendimento     NUMERIC(12,3) NOT NULL DEFAULT 1,   -- quantas porções a receita rende
  unidade_rendimento TEXT,                           -- "porções", "litros"
  observacoes    TEXT,
  atualizado_em  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Ingredientes da ficha. QUANTIDADE sempre na UNIDADE DE ESTOQUE do insumo
-- (0,250 = 250 g de picanha LÍQUIDA). perca_pct = desperdício de pré-preparo
-- (descasca, ossos): a baixa no estoque usa a quantidade BRUTA = liq/(1-perca).
CREATE TABLE ficha_tecnica_item (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ficha_tecnica_id   BIGINT NOT NULL REFERENCES ficha_tecnica (id) ON DELETE CASCADE,
  insumo_id          BIGINT NOT NULL REFERENCES insumo (id),
  quantidade         NUMERIC(12,3) NOT NULL CHECK (quantidade > 0),
  perca_pct        NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (perca_pct BETWEEN 0 AND 99),
  observacao         TEXT                            -- "limpar e picar brunoise", "usar a clara também"
);
CREATE INDEX ix_ft_item_insumo ON ficha_tecnica_item (insumo_id);

-- ----------------------------------------------------------------------------
-- 4. MÓDULO ATENDIMENTO (GARÇOM)
-- ----------------------------------------------------------------------------
CREATE TABLE area (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome   TEXT NOT NULL UNIQUE                       -- Salão, Varanda, Mezanino, Delivery
);

CREATE TABLE mesa (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero      INT  NOT NULL,
  area_id     BIGINT NOT NULL REFERENCES area (id),
  capacidade  SMALLINT NOT NULL DEFAULT 4 CHECK (capacidade > 0),
  status      tipo_status_mesa NOT NULL DEFAULT 'LIVRE',
  -- coordenadas p/ o mapa visual (grid da tela do salão)
  pos_x       SMALLINT,
  pos_y       SMALLINT,
  ativo       BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX ux_mesa_numero ON mesa (numero) WHERE ativo;

CREATE TABLE pedido (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesa_id        BIGINT NOT NULL REFERENCES mesa (id),
  garcom_id      BIGINT REFERENCES usuario (id),
  status         tipo_status_pedido NOT NULL DEFAULT 'ABERTO',
  observacao     TEXT,                               -- "aniversário", "cliente com pressa"
  aberto_em      TIMESTAMPTZ NOT NULL DEFAULT now(), -- início do tempo de ocupação
  fechado_em     TIMESTAMPTZ
);
-- Garante: no máximo UM pedido aberto por mesa
CREATE UNIQUE INDEX ux_pedido_aberto_mesa ON pedido (mesa_id) WHERE status = 'ABERTO';
CREATE INDEX ix_pedido_status ON pedido (status, aberto_em);

-- Remessa = "onda" de envio (1ª: entradas, 2ª: pratos, 3ª: sobremesas).
-- É o que separa o pedido POR TEMPO na cozinha e vira o "cabeçalho" impresso.
CREATE TABLE remessa (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id    BIGINT NOT NULL REFERENCES pedido (id),
  tipo         tipo_remessa NOT NULL DEFAULT 'LIVRE',
  status       tipo_status_remessa NOT NULL DEFAULT 'ENVIADA',
  enviado_em   TIMESTAMPTZ NOT NULL DEFAULT now(),
  enviado_por  BIGINT REFERENCES usuario (id),
  motivo       TEXT                                  -- motivo do cancelamento da remessa inteira
);
CREATE INDEX ix_remessa_pedido ON remessa (pedido_id);

CREATE TABLE pedido_item (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id        BIGINT NOT NULL REFERENCES pedido (id),
  remessa_id       BIGINT REFERENCES remessa (id),   -- NULL = ainda rascunho do garçom, não impresso
  produto_id       BIGINT NOT NULL REFERENCES produto (id),
  quantidade       NUMERIC(12,3) NOT NULL CHECK (quantidade > 0),
  preco_unitario   NUMERIC(12,2) NOT NULL,           -- snapshot do preço no lançamento
  status           tipo_status_item NOT NULL DEFAULT 'RASCUNHO',
  -- Observações livres: "carne ao ponto", "sem cebola", "ponto da batata"
  observacao       TEXT,
  -- Atributos estruturados mais comuns em restaurante (sabor de massa, ponto
  -- da carne etc.). NULL usa o padrão da categoria/produto.
  ponto_carne      TEXT,
  motivo_cancelamento TEXT,
  criado_em        TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em    TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_por   BIGINT REFERENCES usuario (id)    -- quem mudou o status (p/ atribuir gorjeta)
);
CREATE INDEX ix_item_pedido  ON pedido_item (pedido_id);
CREATE INDEX ix_item_remessa ON pedido_item (remessa_id) WHERE remessa_id IS NOT NULL;
CREATE INDEX ix_item_status  ON pedido_item (status);

ALTER TABLE estoque_movimento
  ADD CONSTRAINT fk_estoque_mov_pedido_item
  FOREIGN KEY (pedido_item_id) REFERENCES pedido_item (id);

-- Fila/registro de impressão (o "print agent" local consome esta fila e
-- marca IMPRESSA/FALHA com tentativas — reimpressão vira novo log).
-- Um job por (remessa, estação): itens de cozinha e bar na mesma remessa
-- geram jobs separados automaticamente.
CREATE TABLE impressao_log (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  remessa_id       BIGINT NOT NULL REFERENCES remessa (id),
  estacao_id       BIGINT NOT NULL REFERENCES estacao (id),
  -- PRODUCAO = comanda normal · CANCELAMENTO = ticket avulso quando um item
  -- já enviado é cancelado (a cozinha precisa ver, mesmo que já tenha impresso)
  tipo             TEXT NOT NULL DEFAULT 'PRODUCAO'
                   CHECK (tipo IN ('PRODUCAO', 'CANCELAMENTO')),
  -- EM_IMPRESSAO = claimed por um print-agent (evita impressão duplicada
  -- quando há 2 agentes; claims travados >5 min podem ser retomados).
  status           tipo_status_impressao NOT NULL DEFAULT 'PENDENTE',
  conteudo         TEXT,                    -- comanda renderizada (texto/ESC-POS) montada pelo backend
  tentativas       INT NOT NULL DEFAULT 0,
  criado_em        TIMESTAMPTZ NOT NULL DEFAULT now(),
  ultima_tentativa TIMESTAMPTZ
);
CREATE INDEX ix_impressao_fila ON impressao_log (status, criado_em) WHERE status = 'PENDENTE';
-- Idempotência: no máximo 1 job ativo (pendente ou sendo impresso) por
-- (remessa, estação, tipo). PRODUCAO e CANCELAMENTO coexistem; reimpressão
-- manual cria outro PRODUCAO quando não há job ativo.
CREATE UNIQUE INDEX ux_impressao_job ON impressao_log (remessa_id, estacao_id, tipo)
  WHERE status IN ('PENDENTE', 'EM_IMPRESSAO');

-- ----------------------------------------------------------------------------
-- 5. MÓDULO CONTAS / CAIXA
-- ----------------------------------------------------------------------------
-- Conta = "ponta" da mesa. Uma mesa pode ter N contas quando dividida
-- (divisão por item) — e cada conta aceita N pagamentos.
CREATE TABLE conta (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id        BIGINT NOT NULL REFERENCES pedido (id),
  descricao        TEXT NOT NULL DEFAULT 'Conta 1',  -- "Conta 1 - João", "4ª parte"
  status           tipo_status_conta NOT NULL DEFAULT 'ABERTA',
  incluir_servico  BOOLEAN NOT NULL DEFAULT TRUE,    -- 10% do garçom
  servico_pct      NUMERIC(5,2) NOT NULL DEFAULT 10.00
                   CHECK (servico_pct BETWEEN 0 AND 100), -- snapshot da config
  desconto_valor   NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (desconto_valor >= 0),
  -- DIVISÃO IGUALITÁRIA: quando preenchido, o total desta conta É este
  -- valor (serviço/desconto já embutidos pelo app). Division por item usa
  -- conta_item e deixa este campo NULL.
  valor_rateio     NUMERIC(12,2),
  aberto_em        TIMESTAMPTZ NOT NULL DEFAULT now(),
  fechada_em       TIMESTAMPTZ,
  CHECK (valor_rateio IS NULL OR valor_rateio >= 0)
);
CREATE INDEX ix_conta_pedido ON conta (pedido_id);
CREATE INDEX ix_conta_status ON conta (status);

-- Divisão POR ITEM: quais itens (e quantas unidades deles) pertencem a esta
-- conta. Permite até rachar 1 prato 8x8 em 2 contas (quantidade fracionária).
CREATE TABLE conta_item (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conta_id       BIGINT NOT NULL REFERENCES conta (id) ON DELETE CASCADE,
  pedido_item_id BIGINT NOT NULL REFERENCES pedido_item (id),
  quantidade     NUMERIC(12,3) NOT NULL DEFAULT 1 CHECK (quantidade > 0)
);
CREATE UNIQUE INDEX ux_conta_item ON conta_item (conta_id, pedido_item_id);
CREATE INDEX ix_conta_item_item ON conta_item (pedido_item_id);

CREATE TABLE caixa (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operador_id    BIGINT NOT NULL REFERENCES usuario (id),
  status         tipo_status_caixa NOT NULL DEFAULT 'ABERTO',
  valor_inicial  NUMERIC(12,2) NOT NULL DEFAULT 0,   -- fundo de troco
  aberto_em      TIMESTAMPTZ NOT NULL DEFAULT now(),
  fechado_em     TIMESTAMPTZ,
  valor_contado  NUMERIC(12,2),                       -- digitado na conferência
  diferenca      NUMERIC(12,2),                       -- contado - esperado (calculado no fechamento)
  observacao     TEXT
);
-- 1 caixa aberto por operador (a API também checa e devolve 409 amigável)
CREATE UNIQUE INDEX ux_caixa_aberto_operador ON caixa (operador_id) WHERE status = 'ABERTO';

CREATE TABLE caixa_movimento (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caixa_id    BIGINT NOT NULL REFERENCES caixa (id),
  tipo        tipo_movimento_caixa NOT NULL,          -- SANGRIA | SUPRIMENTO
  valor       NUMERIC(12,2) NOT NULL CHECK (valor > 0),
  motivo      TEXT,
  usuario_id  BIGINT REFERENCES usuario (id),
  criado_em   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE pagamento (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conta_id     BIGINT NOT NULL REFERENCES conta (id),
  caixa_id     BIGINT REFERENCES caixa (id),          -- caixa do operador no momento do pagamento
  forma        tipo_forma_pagamento NOT NULL,
  status       tipo_status_pagamento NOT NULL DEFAULT 'APROVADO', -- PIX/PIX-retorno inicia PENDENTE
  valor        NUMERIC(12,2) NOT NULL CHECK (valor > 0),
  -- troco < valor (líquido sempre positivo — espelha a validação da API)
  valor_troco  NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (valor_troco >= 0 AND valor_troco < valor),
  referencia   TEXT,                                  -- id Pix/cartão (copia-e-cola do app do banco)
  observacao   TEXT,
  pago_em      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_pagamento_caixa ON pagamento (caixa_id, pago_em) WHERE status = 'APROVADO';
CREATE INDEX ix_pagamento_conta ON pagamento (conta_id);

-- ----------------------------------------------------------------------------
-- 6. VIEWS
-- ----------------------------------------------------------------------------
-- Soma dos movimentos → saldo atual por insumo
CREATE VIEW vw_saldo_insumo AS
SELECT
  i.id AS insumo_id,
  i.nome,
  um.sigla AS unidade,
  COALESCE(SUM(CASE
    WHEN m.tipo IN ('ENTRADA', 'AJUSTE_POSITIVO') THEN  m.quantidade
    ELSE -m.quantidade
  END), 0) AS saldo
FROM insumo i
JOIN unidade_medida um ON um.id = i.unidade_estoque_id
LEFT JOIN estoque_movimento m ON m.insumo_id = i.id
WHERE i.ativo
GROUP BY i.id, i.nome, um.sigla;

-- Alertas de estoque mínimo com métricas de "quantos dias aguento"
CREATE VIEW vw_alerta_estoque AS
WITH consumo AS (
  SELECT m.insumo_id,
         SUM(CASE WHEN m.tipo IN ('SAIDA_VENDA','CONSUMO_INTERNO','PERDA')
                  THEN m.quantidade ELSE 0 END) AS consumo_30d
  FROM estoque_movimento m
  WHERE m.data_movimento >= now() - INTERVAL '30 days'
  GROUP BY m.insumo_id
)
SELECT
  s.insumo_id,
  s.nome,
  s.unidade,
  s.saldo,
  i.estoque_minimo,
  c.consumo_30d,
  CASE WHEN c.consumo_30d > 0
       THEN ROUND(s.saldo / (c.consumo_30d / 30.0), 1)
  END AS dias_de_estoque,
  CASE
    WHEN s.saldo <= 0                                    THEN 'SEM_SALDO'
    WHEN s.saldo <= i.estoque_minimo                     THEN 'ABAIXO_DO_MINIMO'
    WHEN c.consumo_30d > 0 AND s.saldo / (c.consumo_30d/30.0) < 3 THEN 'COMPRA_URGENTE'
    ELSE 'OK'
  END AS nivel,
  GREATEST(COALESCE(i.estoque_maximo, i.estoque_minimo * 3) - s.saldo, 0) AS compra_sugerida
FROM vw_saldo_insumo s
JOIN insumo i ON i.id = s.insumo_id
LEFT JOIN consumo c ON c.insumo_id = s.insumo_id;

-- Custo e margem reais de cada prato (considera a PERCA da ficha técnica)
CREATE VIEW vw_custo_produto AS
SELECT
  p.id AS produto_id,
  p.nome,
  p.preco,
  ROUND(COALESCE(SUM(
        (fti.quantidade / (1 - fti.perca_pct / 100.0)) * i.custo_unitario
      ), 0) / GREATEST(f.rendimento, 1), 2) AS custo_por_porcao,
  CASE WHEN p.preco > 0
       THEN ROUND((p.preco - COALESCE(SUM(
              (fti.quantidade / (1 - fti.perca_pct / 100.0)) * i.custo_unitario
            ), 0) / GREATEST(f.rendimento, 1)) / p.preco * 100, 1)
  END AS margem_pct
FROM produto p
LEFT JOIN ficha_tecnica f     ON f.produto_id = p.id
LEFT JOIN ficha_tecnica_item fti ON fti.ficha_tecnica_id = f.id
LEFT JOIN insumo i            ON i.id = fti.insumo_id
WHERE p.ativo
GROUP BY p.id, p.nome, p.preco, f.rendimento;

-- Visão do mapa de mesas: status + tempo de ocupação em minutos
CREATE VIEW vw_mapa_mesas AS
SELECT
  m.id AS mesa_id,
  m.numero,
  a.nome AS area,
  m.capacidade,
  m.status,
  m.pos_x, m.pos_y,
  pr.id AS pedido_id,
  u.nome AS garcom,
  pr.aberto_em,
  CASE WHEN pr.id IS NOT NULL
       THEN FLOOR(EXTRACT(EPOCH FROM (now() - pr.aberto_em)) / 60)
  END AS ocupacao_min
FROM mesa m
JOIN area a ON a.id = m.area_id
LEFT JOIN pedido pr ON pr.mesa_id = m.id AND pr.status = 'ABERTO'
LEFT JOIN usuario u ON u.id = pr.garcom_id
WHERE m.ativo;

-- Resumo de cada conta: subtotal (dos itens ou do rateio), serviço, saldo.
-- Rateio: o valor fechado JÁ inclui base+serviço — o servico_valor é DERIVADO
-- (rateio × pct/(100+pct)) para o recibo mostrar os 10% e a gorjeta do
-- garçom não zerar na divisão igualitária. Total nunca negativo (desconto
-- acima do subtotal zera a conta em vez de gerar saldo negativo).
CREATE VIEW vw_conta_resumo AS
WITH base AS (
  SELECT c.*,
         COALESCE(SUM(ci.quantidade * pi.preco_unitario), 0) AS sub_itens,
         -- subquery escalar: 1 linha por conta (JOIN+GROUP BY duplicaria o pago)
         COALESCE((SELECT SUM(pg.valor - pg.valor_troco) FROM pagamento pg
                   WHERE pg.conta_id = c.id AND pg.status = 'APROVADO'), 0) AS pago
  FROM conta c
  LEFT JOIN conta_item ci ON ci.conta_id = c.id
  LEFT JOIN pedido_item pi ON pi.id = ci.pedido_item_id AND pi.status <> 'CANCELADO'
  WHERE c.status <> 'CANCELADA'
  GROUP BY c.id
),
tot AS (
  SELECT b.*,
    CASE WHEN b.valor_rateio IS NOT NULL THEN
           CASE WHEN b.incluir_servico
                THEN ROUND(b.valor_rateio * b.servico_pct / (100 + b.servico_pct), 2)
                ELSE 0 END
         WHEN b.incluir_servico THEN ROUND(b.sub_itens * b.servico_pct / 100, 2)
         ELSE 0
    END AS servico_valor
  FROM base b
)
SELECT
  id AS conta_id,
  pedido_id,
  descricao,
  status,
  CASE WHEN valor_rateio IS NOT NULL THEN 0 ELSE ROUND(sub_itens, 2) END AS subtotal_itens,
  valor_rateio,
  servico_valor,
  desconto_valor,
  GREATEST(ROUND(CASE WHEN valor_rateio IS NOT NULL THEN valor_rateio
                      ELSE sub_itens + servico_valor END, 2) - desconto_valor, 0) AS total,
  pago,
  GREATEST(ROUND(CASE WHEN valor_rateio IS NOT NULL THEN valor_rateio
                      ELSE sub_itens + servico_valor END, 2) - desconto_valor, 0) - pago AS saldo
FROM tot;

-- Fechamento de caixa: esperado por forma vs. digitado.
-- Usa subqueries escalares (NUNCA joins com GROUP BY aqui: pagamento ×
-- caixa_movimento formaria produto cartesiano e duplicaria os totais).
CREATE VIEW vw_caixa_resumo AS
SELECT
  cx.id AS caixa_id,
  u.nome AS operador,
  cx.status,
  cx.aberto_em,
  cx.valor_inicial,
  COALESCE((SELECT SUM(p.valor - p.valor_troco) FROM pagamento p
            WHERE p.caixa_id = cx.id AND p.status='APROVADO' AND p.forma='DINHEIRO'), 0)      AS dinheiro,
  COALESCE((SELECT SUM(p.valor) FROM pagamento p
            WHERE p.caixa_id = cx.id AND p.status='APROVADO' AND p.forma='PIX'), 0)           AS pix,
  COALESCE((SELECT SUM(p.valor) FROM pagamento p
            WHERE p.caixa_id = cx.id AND p.status='APROVADO' AND p.forma='CARTAO_CREDITO'), 0) AS cartao_credito,
  COALESCE((SELECT SUM(p.valor) FROM pagamento p
            WHERE p.caixa_id = cx.id AND p.status='APROVADO' AND p.forma='CARTAO_DEBITO'), 0)  AS cartao_debito,
  COALESCE((SELECT SUM(p.valor) FROM pagamento p
            WHERE p.caixa_id = cx.id AND p.status='APROVADO'
              AND p.forma IN ('VALE_ALIMENTACAO','VALE_REFEICAO')), 0)                          AS vales,
  COALESCE((SELECT SUM(p.valor) FROM pagamento p
            WHERE p.caixa_id = cx.id AND p.status='APROVADO' AND p.forma='OUTRO'), 0)          AS outros,
  COALESCE((SELECT SUM(p.valor - p.valor_troco) FROM pagamento p
            WHERE p.caixa_id = cx.id AND p.status='APROVADO'), 0)                              AS total_vendido,
  COALESCE((SELECT SUM(k.valor) FROM caixa_movimento k
            WHERE k.caixa_id = cx.id AND k.tipo='SUPRIMENTO'), 0)                              AS suprimentos,
  COALESCE((SELECT SUM(k.valor) FROM caixa_movimento k
            WHERE k.caixa_id = cx.id AND k.tipo='SANGRIA'), 0)                                AS sangrias,
  cx.valor_inicial
    + COALESCE((SELECT SUM(p.valor - p.valor_troco) FROM pagamento p
                WHERE p.caixa_id = cx.id AND p.status='APROVADO'), 0)
    + COALESCE((SELECT SUM(k.valor) FROM caixa_movimento k
                WHERE k.caixa_id = cx.id AND k.tipo='SUPRIMENTO'), 0)
    - COALESCE((SELECT SUM(k.valor) FROM caixa_movimento k
                WHERE k.caixa_id = cx.id AND k.tipo='SANGRIA'), 0)                             AS valor_esperado,
  -- conferência da GAVETA: só o que é físico (fundo + dinheiro − trocos +
  -- suprimentos − sangrias). Cartão/PIX conferem pelo extrato da adquirente.
  cx.valor_inicial
    + COALESCE((SELECT SUM(p.valor - p.valor_troco) FROM pagamento p
                WHERE p.caixa_id = cx.id AND p.status='APROVADO' AND p.forma='DINHEIRO'), 0)
    + COALESCE((SELECT SUM(k.valor) FROM caixa_movimento k
                WHERE k.caixa_id = cx.id AND k.tipo='SUPRIMENTO'), 0)
    - COALESCE((SELECT SUM(k.valor) FROM caixa_movimento k
                WHERE k.caixa_id = cx.id AND k.tipo='SANGRIA'), 0)                             AS valor_esperado_dinheiro,
  cx.valor_contado,
  cx.diferenca
FROM caixa cx
JOIN usuario u ON u.id = cx.operador_id;

-- Gorjeta a repassar por garçom (soma do serviço das contas fechadas)
CREATE VIEW vw_gorjeta_garcom AS
SELECT
  u.id AS garcom_id,
  u.nome,
  DATE_TRUNC('month', pr.fechado_em)::date AS mes,
  ROUND(SUM(vcr.servico_valor), 2) AS gorjeta_total
FROM conta c
JOIN vw_conta_resumo vcr ON vcr.conta_id = c.id
JOIN pedido pr ON pr.id = c.pedido_id AND pr.status = 'FECHADO'
JOIN usuario u ON u.id = pr.garcom_id
WHERE c.status = 'FECHADA' AND c.incluir_servico
GROUP BY u.id, u.nome, DATE_TRUNC('month', pr.fechado_em);

-- ----------------------------------------------------------------------------
-- 7. FUNÇÕES & TRIGGERS (regras de negócio no banco p/ não deixar escapar)
-- ----------------------------------------------------------------------------

-- 7.1 Baixa automática de estoque na venda (e estorno no cancelamento).
-- Regra: deduz BRUTO = quantidade/(1 - perca%) da ficha, por unidade vendida.
-- O ponto de acionamento respeita config_restaurante.baixa_estoque_em.
CREATE OR REPLACE FUNCTION fn_item_baixa_estoque() RETURNS trigger AS $$
DECLARE
  v_baixa_em   TEXT;
  v_ja_baixado BOOLEAN;
BEGIN
  SELECT cfg.baixa_estoque_em INTO v_baixa_em FROM config_restaurante cfg WHERE cfg.id = 1;
  v_baixa_em := COALESCE(v_baixa_em, 'ENVIO');

  -- Estorno: item que JÁ baixou estoque foi cancelado
  IF TG_OP = 'UPDATE'
     AND NEW.status = 'CANCELADO' AND OLD.status <> 'CANCELADO' THEN
    INSERT INTO estoque_movimento
      (insumo_id, tipo, quantidade, custo_unitario, origem, pedido_item_id, usuario_id, motivo)
    SELECT m.insumo_id, 'AJUSTE_POSITIVO'::tipo_movimento_estoque, m.quantidade, m.custo_unitario,
           'CANCELAMENTO_ITEM'::tipo_origem_movimento, NEW.id, NEW.atualizado_por,
           'Estorno: item #' || NEW.id || ' cancelado (estava ' || OLD.status || ')'
    FROM estoque_movimento m
    WHERE m.pedido_item_id = NEW.id AND m.tipo = 'SAIDA_VENDA';
    RETURN NULL;
  END IF;

  IF NEW.status IN ('ENVIADO', 'EM_PREPARO', 'PRONTO', 'ENTREGUE') THEN
    SELECT EXISTS (
      SELECT 1 FROM estoque_movimento m
      WHERE m.pedido_item_id = NEW.id AND m.tipo = 'SAIDA_VENDA'
    ) INTO v_ja_baixado;

    IF NOT v_ja_baixado THEN
      IF (v_baixa_em = 'ENVIO')
         OR (v_baixa_em = 'PRONTO'   AND NEW.status IN ('PRONTO', 'ENTREGUE'))
         OR (v_baixa_em = 'ENTREGA'  AND NEW.status = 'ENTREGUE') THEN

        -- 1) Via ficha técnica (pratos): baixa BRUTA, proporcional ao
        --    rendimento da receita (1 fatia de um pudim q rende 10 baixa 1/10)
        INSERT INTO estoque_movimento
          (insumo_id, tipo, quantidade, custo_unitario, origem, pedido_item_id, usuario_id, motivo)
        SELECT fti.insumo_id,
               'SAIDA_VENDA'::tipo_movimento_estoque,
               ROUND(fti.quantidade / (1 - fti.perca_pct / 100.0)
                     * NEW.quantidade / GREATEST(f.rendimento, 1), 3),
               i.custo_unitario,
               'BAIXA_VENDA'::tipo_origem_movimento,
               NEW.id,
               NEW.atualizado_por,
               'Venda: ' || p.nome || ' x' || NEW.quantidade
        FROM produto p
        JOIN ficha_tecnica f      ON f.produto_id = p.id
        JOIN ficha_tecnica_item fti ON fti.ficha_tecnica_id = f.id
        JOIN insumo i             ON i.id = fti.insumo_id
        WHERE p.id = NEW.produto_id
        UNION ALL
        -- 2) Produto vinculado 1:1 a um insumo (bebidas fechadas etc.)
        SELECT p.insumo_vinculado_id,
               'SAIDA_VENDA',
               NEW.quantidade,
               i.custo_unitario,
               'BAIXA_VENDA'::tipo_origem_movimento,
               NEW.id,
               NEW.atualizado_por,
               'Venda: ' || p.nome || ' x' || NEW.quantidade
        FROM produto p
        JOIN insumo i ON i.id = p.insumo_vinculado_id
        WHERE p.id = NEW.produto_id
          AND p.insumo_vinculado_id IS NOT NULL
          AND NOT EXISTS (SELECT 1 FROM ficha_tecnica f WHERE f.produto_id = p.id);
      END IF;
    END IF;
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_item_baixa_estoque
AFTER INSERT OR UPDATE OF status ON pedido_item
FOR EACH ROW EXECUTE FUNCTION fn_item_baixa_estoque();

-- 7.2 Envio de itens → enfileira UM job de impressão por (remessa, estação).
-- Dispara no pedido_item (não na remessa): quando o garçom aperta "enviar",
-- os itens passam a ENVIADO e cada estação envolvida (cozinha E/OU bar)
-- ganha seu próprio job, mesmo dentro da mesma remessa. O print agent da LAN
-- consome a fila e imprime via ESC/POS. Impresso é um novo job manual.
CREATE OR REPLACE FUNCTION fn_item_fila_impressao() RETURNS trigger AS $$
DECLARE
  v_estacao BIGINT;
BEGIN
  IF NEW.status = 'ENVIADO'
     AND (TG_OP = 'INSERT' OR OLD.status IS DISTINCT FROM 'ENVIADO')
     AND NEW.remessa_id IS NOT NULL THEN

    -- resolve a estação do produto: override do produto > padrão da categoria
    SELECT COALESCE(p.estacao_id, cat.estacao_id) INTO v_estacao
    FROM produto p
    JOIN categoria cat ON cat.id = p.categoria_id
    WHERE p.id = NEW.produto_id;

    IF v_estacao IS NOT NULL THEN
      INSERT INTO impressao_log (remessa_id, estacao_id, tipo)
      VALUES (NEW.remessa_id, v_estacao, 'PRODUCAO')
      ON CONFLICT (remessa_id, estacao_id, tipo) WHERE status IN ('PENDENTE', 'EM_IMPRESSAO')
      DO NOTHING;   -- já existe job ativo p/ esta estação nesta remessa
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_item_fila_impressao
AFTER INSERT OR UPDATE OF status ON pedido_item
FOR EACH ROW EXECUTE FUNCTION fn_item_fila_impressao();

-- 7.2b Cancelamento de item enviado → ticket de CANCELAMENTO na estação certa.
-- (Fase 2: a cozinha/bar precisa VER o cancelamento, mesmo que já tenha
-- impresso a comanda original — o print-agent imprime este ticket avulso.)
-- Vários cancelamentos da mesma (remessa, estação) acumulam num único ticket
-- pendente (conteúdo concatenado) em vez de um papel para cada item.
CREATE OR REPLACE FUNCTION fn_item_fila_cancelamento() RETURNS trigger AS $$
DECLARE
  v_estacao BIGINT;
  v_texto   TEXT;
BEGIN
  IF NEW.status = 'CANCELADO'
     AND OLD.status IN ('ENVIADO', 'EM_PREPARO', 'PRONTO', 'ENTREGUE')
     AND NEW.remessa_id IS NOT NULL THEN

    SELECT COALESCE(p.estacao_id, cat.estacao_id) INTO v_estacao
    FROM produto p
    JOIN categoria cat ON cat.id = p.categoria_id
    WHERE p.id = NEW.produto_id;

    IF v_estacao IS NOT NULL THEN
      SELECT 'CANCELADO: ' || NEW.quantidade::TEXT || 'x ' || p.nome ||
             COALESCE(' — ' || NULLIF(NEW.motivo_cancelamento, ''), '')
      INTO v_texto
      FROM produto p WHERE p.id = NEW.produto_id;

      INSERT INTO impressao_log (remessa_id, estacao_id, tipo, conteudo)
      VALUES (NEW.remessa_id, v_estacao, 'CANCELAMENTO', v_texto)
      ON CONFLICT (remessa_id, estacao_id, tipo) WHERE status IN ('PENDENTE', 'EM_IMPRESSAO')
      DO UPDATE SET conteudo = impressao_log.conteudo || E'\n' || EXCLUDED.conteudo;
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_item_fila_cancelamento
AFTER UPDATE OF status ON pedido_item
FOR EACH ROW EXECUTE FUNCTION fn_item_fila_cancelamento();

-- 7.3 Ciclo de vida da mesa: abrir pedido ocupa; fechar/cancelar libera.
-- (AGUARDANDO_CONTA é definido pelo app quando o garçom/caixa imprime a conta)
CREATE OR REPLACE FUNCTION fn_pedido_status_mesa() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE mesa SET status = 'OCUPADA' WHERE id = NEW.mesa_id;
  ELSIF TG_OP = 'UPDATE' AND NEW.status <> 'ABERTO' AND OLD.status = 'ABERTO' THEN
    UPDATE mesa SET status = 'LIVRE' WHERE id = NEW.mesa_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_pedido_status_mesa
AFTER INSERT OR UPDATE OF status ON pedido
FOR EACH ROW EXECUTE FUNCTION fn_pedido_status_mesa();

-- 7.4 Rateio por item: proíbe alocar mais unidades do que foi pedido
CREATE OR REPLACE FUNCTION fn_valida_rateio_itens() RETURNS trigger AS $$
DECLARE
  v_total NUMERIC(12,3);
  v_pedido NUMERIC(12,3);
BEGIN
  SELECT COALESCE(SUM(ci.quantidade), 0) INTO v_total
  FROM conta_item ci
  WHERE ci.pedido_item_id = NEW.pedido_item_id;

  SELECT pi.quantidade INTO v_pedido FROM pedido_item pi WHERE pi.id = NEW.pedido_item_id;

  IF v_total > v_pedido THEN
    RAISE EXCEPTION 'Rateio excede o item: % unidade(s) alocadas de %', v_total, v_pedido
      USING HINT = 'Ajuste as quantidades nas contas da mesa.';
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_valida_rateio_itens
AFTER INSERT OR UPDATE ON conta_item
FOR EACH ROW EXECUTE FUNCTION fn_valida_rateio_itens();

-- 7.5 Atualiza atualizado_em do item (dispara baixa/cancelamento com data certa)
CREATE OR REPLACE FUNCTION fn_touch_pedido_item() RETURNS trigger AS $$
BEGIN
  NEW.atualizado_em := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_touch_pedido_item
BEFORE UPDATE ON pedido_item
FOR EACH ROW EXECUTE FUNCTION fn_touch_pedido_item();

COMMIT;
